apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: crossplane-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jolo1993/crossplane-box
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-resources
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: crossplane-repo
  path: yaml
  prune: true
  validation: client
  force: false

